# Generated by Django 2.0.13 on 2019-12-16 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
