# Generated by Django 2.0.13 on 2019-12-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=25)),
                ('location', models.CharField(max_length=25)),
            ],
        ),
    ]
